{% set name = "cgatshowcase" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e24ba2bfb57af4c2b1494cd9826701a67a9400518ef546783d0d89d34dd9124

build:
  skip: True # [not py3k]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - bx-python
    - cgat-scripts
    - quicksect
    - r-base=3.4.1

  run:
    - python
    - multiqc
    - bx-python
    - cgatcore
    - kallisto
    - cgat-scripts
    - quicksect
    - r-base=3.4.1
    - bioconductor-biomart=2.36.1
    - bioconductor-deseq2=1.18.1
    - bioconductor-genomeinfodb=1.14.0
    - bioconductor-rhdf5=2.24.0
    - bioconductor-tximport=1.8.0
    - bioconductor-clusterprofiler
    - bioconductor-org.hs.eg.db
    - bioconductor-limma
    - bioconductor-xvector
    - r-optparse
    - r-ggplot2
    - r-dt
    - python-drmaa
    - r-rmarkdown
    - r-pheatmap
    - r-tidyverse
test:
  imports:
    - cgatshowcase
  commands:
    - cgatshowcase --help >& /dev/null

about:
  home: https://github.com/cgat-developers/cgat-showcase
  license: MIT
  license_family: MIT
  summary: The Computational Genomics Analysis Toolkit example pipeline/workflow

extra:
  recipe-maintainers:
    - 12068583
